export const ACTION = {
  LOAD_PROJECTS: 'LOAD_PROJECTS',
  LOAD_PROJECTS_COMPLETED: 'LOAD_PROJECTS_COMPLETED',

  SELECT_PROJECT: 'SELECT_PROJECT',
  LOAD_COURSES: 'LOAD_COURSES',
  LOAD_COURSES_COMPLETED: 'LOAD_COURSES_COMPLETED',

  LOAD_GRAPH: 'LOAD_GRAPH',
  LOAD_GRAPH_COMPLETED: 'LOAD_GRAPH_COMPLETED'
};
